#!/usr/bin/env python3
"""Generate compact, sorted Unicode and HTML5 entity tables used by chmd.

The generated file is committed so building the library has no Python or
network dependency. Python's tables are sourced from the Unicode database and
WHATWG HTML5 entity list shipped with the standard library.
"""

from html.entities import html5
from pathlib import Path
import unicodedata


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "src" / "generated_tables.inc"


def ranges(points):
    points = iter(points)
    try:
        first = last = next(points)
    except StopIteration:
        return []
    result = []
    for point in points:
        if point == last + 1:
            last = point
        else:
            result.append((first, last))
            first = last = point
    result.append((first, last))
    return result


def cp(value):
    return f"0x{value:X}U"


def main():
    whitespace = ranges(
        value for value in range(0x110000)
        if unicodedata.category(chr(value)) == "Zs" or value in (9, 10, 12, 13)
    )
    punctuation = ranges(
        value for value in range(0x110000)
        if unicodedata.category(chr(value))[0] in ("P", "S")
    )
    folds = []
    for value in range(0x110000):
        folded = chr(value).casefold()
        if folded != chr(value):
            values = [ord(ch) for ch in folded]
            if len(values) <= 3:
                folds.append((value, values))

    entities = {}
    for name, value in html5.items():
        if name.endswith(";"):
            entities[name[:-1]] = [ord(ch) for ch in value]

    with OUTPUT.open("w", encoding="utf-8", newline="\n") as out:
        out.write("// Generated by tools/generate_tables.py; do not edit.\n")
        out.write("struct Range { std::uint32_t first, last; };\n")
        out.write("struct Fold { std::uint32_t source, a, b, c; std::uint8_t count; };\n")
        out.write("struct Entity { std::string_view name; std::uint32_t a, b; std::uint8_t count; };\n\n")

        out.write("static constexpr Range whitespace_ranges[] = {\n")
        for first, last in whitespace:
            out.write(f"    {{{cp(first)}, {cp(last)}}},\n")
        out.write("};\n\n")

        out.write("static constexpr Range punctuation_ranges[] = {\n")
        for first, last in punctuation:
            out.write(f"    {{{cp(first)}, {cp(last)}}},\n")
        out.write("};\n\n")

        out.write("static constexpr Fold case_folds[] = {\n")
        for source, values in folds:
            padded = values + [0] * (3 - len(values))
            out.write(
                f"    {{{cp(source)}, {cp(padded[0])}, {cp(padded[1])}, "
                f"{cp(padded[2])}, {len(values)}}},\n"
            )
        out.write("};\n\n")

        out.write("static constexpr Entity html_entities[] = {\n")
        for name in sorted(entities):
            values = entities[name]
            padded = values + [0] * (2 - len(values))
            escaped = name.replace("\\", "\\\\").replace('"', '\\"')
            out.write(
                f'    {{"{escaped}", {cp(padded[0])}, {cp(padded[1])}, {len(values)}}},\n'
            )
        out.write("};\n")

    print(f"generated {OUTPUT} ({OUTPUT.stat().st_size} bytes)")


if __name__ == "__main__":
    main()

